title: With Associates Notebook
email: hello@withassociates.com
description: >
  We plan, design and build digital services, websites and apps. This is our notebook.
baseurl: ""
url: "http://withassociates.github.io"
markdown: kramdown
